name: Services Docker Publish

on:
  release:
    types: [published]
  push:
    tags:
      - "v*.*.*"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  publish-middleware:
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Set release version
        id: vars
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${DOCKERHUB_USERNAME}/ser516-middleware:${RELEASE_TAG}
          docker build \
            -t "$IMAGE_NAME" \
            -f DockerfileGateway \
            .

      - name: Push Docker image
        run: |
          IMAGE_NAME=${DOCKERHUB_USERNAME}/ser516-middleware:${RELEASE_TAG}
          docker push "$IMAGE_NAME"

      - name: Tag and push latest
        run: |
          VERSIONED_IMAGE=${DOCKERHUB_USERNAME}/ser516-middleware:${RELEASE_TAG}
          LATEST_IMAGE=${DOCKERHUB_USERNAME}/ser516-middleware:latest
          docker tag "$VERSIONED_IMAGE" "$LATEST_IMAGE"
          docker push "$LATEST_IMAGE"
